### ISSUE TITLE
aireplay 参数解释错误纠正

### ISSUE THREAD

**Issue by uncat** [tiancode/learn-hacking#1]
你的文章写得很好,很感谢. 在阅读这篇文章( [Kali Linux使用Aircrack破解wifi密码(wpa/wpa2)](http://topspeedsnail.com/kali-linux-crack-wifi-wpa/) ) 的过程发现一个错误(aireplay -0参数表示发起deauthentication攻击),您的解释错误了.

**Comment by uncat** [comment]
[参阅这篇文档](https://www.aircrack-ng.org/doku.php?id=deauthentication)

**Comment by tiancode** [comment]
谢谢纠正
